Oauth save option
didclab/onedatashare pull request #234
Opened 2019-09-23 21:23 UTC by aashish-jain

Added functionality to save tokens on the front-end.

2019-09-23 21:26 UTC, aashish-jain commented
![](https://github.trello.services/images/mini-trello-icon.png) [OAuth cancel scenario](https://trello.com/c/DzVnJCnq/7-oauth-cancel-scenario)

2019-09-23 21:26 UTC, aashish-jain commented
![](https://github.trello.services/images/mini-trello-icon.png) [OAuth storage preference](https://trello.com/c/UnnQ1cjI/10-oauth-storage-preference)

2019-09-23 21:27 UTC, aashish-jain commented
![](https://github.trello.services/images/mini-trello-icon.png) [Account preference pop up](https://trello.com/c/bJZQ8ukd/6-account-preference-pop-up)

2019-09-24 02:00 UTC, LinusCastelino reviewed
@aashish-jain 
If you have time to spare, please create javadoc comments for every backend method you created or edited.
I can help if required.

2019-09-26 21:35 UTC, aashish-jain commented
@LinusCastelino added the javadoc comments for the controllers

2019-09-26 22:08 UTC, LinusCastelino requested changes

2019-09-26 22:08 UTC, LinusCastelino commented on src/main/java/org/onedatashare/server/service/oauth/OauthService.java
> +        config = DbxRequestConfig.newBuilder("OneDataShare-DIDCLab").build();
Move the application name to ODS Constants

2019-09-26 22:08 UTC, LinusCastelino commented on src/main/java/org/onedatashare/server/model/useraction/UserAction.java
>  import com.fasterxml.jackson.annotation.JsonInclude;
Please add javadocs here

2019-09-26 22:26 UTC, LinusCastelino reviewed
Approving changes since the PR is huge.
Issues raised out of this PR will be treated as bugs.

2019-09-26 22:28 UTC, merged