Lost validation code fix
didclab/onedatashare pull request #237
Opened 2019-09-29 20:29 UTC by KiranPrabhakar135

Fixed the lost validation code page load issue.
Modified the logic to remove the duplicate redirect to the same route. This removes the error in the console for redirect to same url.
Altered the logic for getting the user back to sign page if the user has not chosen the remember me chk box.
Introduced new friendly route for forgot password.
Fixed the broken back to sign button functionality in Forgot password, register and lost validation code components.
made changes to code to avoid redundant verify email check  when registering the user.

2019-09-30 15:17 UTC, aashish-jain approved these changes
Looks good. Please merge after Linus / Yifu have a look into it.

2019-09-30 15:40 UTC, LinusCastelino approved these changes
Good job with clearing the quirky flags. Comments made it easy to understand.
Remember accounts feature needs rework - but that will be a different task.
Approved.

Suggestion - the variable 'validateEmailPressed' is misleading. Please rename to 'lostValidationCodePressed'

2019-09-30 17:06 UTC, LinusCastelino requested changes

2019-09-30 17:06 UTC, LinusCastelino commented on src/main/react-front-end/src/views/Login/CreateAccountComponent.js
> -            onSubmit={this.onEmailNextClicked}>
We need to check if the email is already present in the database before registering incase the user tries to create an account with an already existing email address. Please revert this change.

2019-10-01 22:01 UTC, KiranPrabhakar135 commented
Incorporated review comments

2019-10-01 22:53 UTC, LinusCastelino approved these changes
Looks good to merge

2019-10-01 22:53 UTC, merged